[package]
name = "seryu"
version = "0.1.0"
edition = "2024"

[dependencies]
genos.workspace = true

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace]
resolver = "3"
members = ["example"]

[workspace.dependencies]
genos = { git = "https://github.com/ariaandika/genos.git", rev = "6198a9b", version = "0.1.0" }
